#FROM is to specify my base image. its also always the first line of a docker file
FROM busybox:stable

#WORKDIR TO add a path for my working directory
WORKDIR /Users/j44jum/docker-fundamentals

#CMD this is to define my default commad
CMD ["date", "-u", "+%Y-%m-%dTH:%M:%S"]